# my global config
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
#  - job_name: 'retrieve_targets_from_file'
#    file_sd_configs:
#      - files:
#        - "targets.json"
#        refresh_interval: 10s
#    relabel_configs:
#      - source_labels: [__meta_http_sd_label_instance]
#        target_label: instance

    - job_name: 'retrieve_targets_from_api'
      http_sd_configs:
        - url: 'http://127.0.0.1:8123/targets'
          refresh_interval: 10s
      relabel_configs:
        - source_labels: [__meta_http_sd_label_instance]
          target_label: instance
